version: '2'

services:
   db:
     image: mysql:5.7
     networks:
       - test2snapshot_network     
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     networks:
       - test2snapshot_network
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
   redis:
     image: redis:4.0
     networks:
       - test2snapshot_network
   nexus:
     image: 'sonatype/nexus3:3.20.1'  
     networks:
       - test2snapshot_network

networks:
   test2snapshot_network: 
      external: true
